name: OWASP ZAP Scan on Juice Shop (Docker)

on:
  push:
    branches:
      - main
    paths:
      - 'Security_Compliance_workshop-dhiraj/day2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Security_Compliance_workshop-dhiraj/day2/**'

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Run OWASP ZAP Baseline Scan
      run: |
        sudo chown 1000:1000 ${{ github.workspace }}
        docker run --rm -v ${{ github.workspace }}:/zap/wrk \
          ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
          -t https://juice-shop.herokuapp.com/ \
          -g gen.conf \
          -J report_json.json \
          -w report_md.md \
          -r zap-report.html || true
          
    - name: List generated reports
      run: ls -lh ${{ github.workspace }}      

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: |
          ${{ github.workspace }}/report_json.json
          ${{ github.workspace }}/report_md.md
          ${{ github.workspace }}/zap-report.html

    - name: Download ZAP Report
      uses: actions/download-artifact@v4
      with:
        name: zap-report
        path: pi-shaped-workshop-dhiraj/Security_Compliance_workshop-dhiraj/day2/